parser_name: alert_detail_settings

match:
  source: "*"

display:
  layout: accordion

  sections:
    - title: Overview
      fields:
        - field: source
          label: Source

        - field: severity
          label: Severity
          style: severity_level
          translate:
            1: "low"
            2: "low"
            3: "low"
            4: "low"
            5: "low"
            6: "medium"
            7: "medium"
            8: "medium"
            9: "medium"
            10: "High"
            11: "High"
            12: "High"
            13: "High"
            14: "High"
            15: "critical"
          color_map:
            critical: "#dc3545"
            high: "#FF0000"
            medium: "#ffc107"
            low: "#198754"
            unknown: "#6c757d"

        - field: status
          label: Status
          style: badge
          translate:
            done: "Done"
            in_progress: "In Progress"
            new: "New"
          color_map:
            new: "#ff0000"
            in progress: "#00FF00"
            done: "#0000FF"

        - field: resolution
          label: Resolution
          style: badge
          translate:
            under_investigation: "Under Investigation"
            false_positive: "False Positive"
            true_positive_no_impact: "TP (No Impact)"
            true_positive_with_impact: "TP (Impact)"
            not_applicable: "Not Applicable"
            legitimate: "Legitimate"
            unknown: "Unknown"
            "-": "empty"
          color_map:
            under_investigation: "#0dcaf0"
            true_positive_no_impact: "#ffc107"
            true_positive_with_impact: "#dc3545"
            "not applicable": "#adb5bd"
            legitimate: "#198754"
            unknown: "#6c757d"
            false positive: "#FF0000"
            "": "#"

        - field: tags
          label: Tags
          style: tag_list

        - field: source_event_time
          label: Source Event Time

        - field: created_at
          label: Created At

    - title: Message
      fields:
        - field: message
          label: Message
          style: default
          no_label: true

    - title: Parsed Fields
      source: parsed_fields
      style: auto

    - title: Tags
      source: parsed_tags
      style: tag_list
      no_label: true

    - title: Enrichment
      source: parsed_enrichment
      style: json

    - title: Source Payload
      source: source_payload
      style: json

    - title: Observables
      fields:
        - field: observables
          style: json
          no_label: true

