version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sentinel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sentinel_user
      POSTGRES_PASSWORD: sentinel_pass
      POSTGRES_DB: sentinel_db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
