"""Add agent fields to alerts

Revision ID: 007061ad3e8f
Revises: 
Create Date: 2025-07-06 18:11:29.476241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007061ad3e8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('agent_id', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('agent_name', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('agent_ip', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('rule_id', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('rule_description', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('payload_flat_text', sa.String(), nullable=True))
    op.create_index(op.f('ix_alerts_agent_id'), 'alerts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_alerts_agent_ip'), 'alerts', ['agent_ip'], unique=False)
    op.create_index(op.f('ix_alerts_agent_name'), 'alerts', ['agent_name'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_agent_name'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_agent_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_agent_id'), table_name='alerts')
    op.drop_column('alerts', 'payload_flat_text')
    op.drop_column('alerts', 'rule_description')
    op.drop_column('alerts', 'rule_id')
    op.drop_column('alerts', 'agent_ip')
    op.drop_column('alerts', 'agent_name')
    op.drop_column('alerts', 'agent_id')
    # ### end Alembic commands ###
