"""add alert_enrichments table

Revision ID: 5826025d46df
Revises: 007061ad3e8f
Create Date: 2025-07-07 18:59:13.166808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5826025d46df'
down_revision: Union[str, Sequence[str], None] = '007061ad3e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_enrichments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('enrichment_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_enrichments_alert_id'), 'alert_enrichments', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_enrichments_enrichment_type'), 'alert_enrichments', ['enrichment_type'], unique=False)
    op.create_index(op.f('ix_alert_enrichments_id'), 'alert_enrichments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_enrichments_id'), table_name='alert_enrichments')
    op.drop_index(op.f('ix_alert_enrichments_enrichment_type'), table_name='alert_enrichments')
    op.drop_index(op.f('ix_alert_enrichments_alert_id'), table_name='alert_enrichments')
    op.drop_table('alert_enrichments')
    # ### end Alembic commands ###
